name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        working-directory: mobile/dogmine_app
        run: flutter pub get

      - name: Flutter analyze
        working-directory: mobile/dogmine_app
        run: flutter analyze

      - name: Flutter test
        working-directory: mobile/dogmine_app
        run: flutter test
